sudo: required
services:
    - docker

before_install:
    - docker build -t bhgray/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bhgray/docker-react npm run test

deploy:
    # edge: true
    # provider: elasticbeanstalk
    # region: "us-east-1"
    # app: "docker-react"
    # env: "DockerReact-env"
    # bucket_name: "elasticbeanstalk-us-east-1-117214242521"
    # bucket_path: "docker-react"
    # on: 
    #     branch: master
    # access_key_id: $AWS_ACCESS_KEY
    # secret_access_key: $AWS_SECRET_KEY
    edge: true
    verbose: true
    # username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
    # password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
    site: "docker-react"       # If AZURE_WA_SITE isn't set